import type { Metadata } from "next";
import { Alumni_Sans_Pinstripe, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";

const alumniSans = Alumni_Sans_Pinstripe({
  subsets: ["latin"],
  variable: "--font-alumni-sans",
  display: "swap",
  weight: "400",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-merriweather",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alumniSans.variable} ${merriweather.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
